# Format with "cargo +nightly fmt --all"

style_edition     = "2024"
unstable_features = true

format_code_in_doc_comments = true
format_macro_bodies         = true
format_macro_matchers       = true
format_strings              = true
group_imports               = "StdExternalCrate"
imports_granularity         = "Crate"
newline_style               = "Unix"
use_small_heuristics        = "Max"
wrap_comments               = true
